language: node_js
node_js:
- '6'
env:
  global:
  - CXX=g++-4.8
  - DEPLOY_BRANCH=master
  - STAGING_BRANCH=develop
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
cache:
  apt: true
  yarn: true
  directories:
  - node_modules
services:
- docker
before_script:
- yarn test
script:
- yarn run build
deploy:
  provider: s3
  access_key_id: AKIAILREAKXPJOWAXTBQ
  secret_access_key:
    secure: lUPMervRELFiJkiFLbNLsPLEUrfPhtYz2xzu52YuYpUeI/f3BUcFBbWoKqJBHm25qex6/rE0pWnYe3VJQMsm1vskaWB6IzYT+q4aszUvRCMSvmzj7y4aka7E75m9dXyazOEnVgbCz3QxTSIz0TC//Res9lW9+Z6tSwDGGBcMFVH4l0yLV/Ny3qjdsBTH1s/iH+Ff3X900wY/mZQ38tU4vKgRs8yY/ipWvqs+M9EKFDlJkvR1iNyamI/WU17UM9lyF20cGG3pSJhBGWssgq/eGZion5caDTdeWAXDO7Is5s8g8M0VKhf3zTj4H/NgAkZRIxKVGPZU4r+/BaXFADLGm0QxDGn0VjytH54kyXghzIhUjv3k4tRfsPg/OnGzqz1nFGJKjEu9KOP7gmgfLIhenTsbc728u4VWqIqMz8A3dMSnJAaeB+eonozqwX3lW06n1byP4deGcZwZ4FOoQ140cQc8A2n+LMkmOolsCJt/VWeKIX/VMM3+sJ7CApKnEgA3+VqDRPxzlu6mFvt1M0ZiPTuuaHxwaFlfQkFRPXD4TQT3FLCoklnLgmbr3AE/Zz7wZP/IySMq01fL278isWgqciwwpIA+1cS0T0wKue1J2hAwuI0YVz8knXRRlSseGezyzfc/ceXk/S/IJi+VuG0J+aXtW/QlQBxCtFr8HOfpT9Y=
  bucket: accessibility.devseed.com
  local-dir: "./dist"
  skip-cleanup: true
  acl: public_read
  on:
    repo: developmentseed/ram-frontend
    branch: "${DEPLOY_BRANCH}"
